# Generated by Django 4.2.7 on 2023-11-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название курса ')),
                ('image', models.ImageField(upload_to='media/hoto/cours/%d', verbose_name='Загрузите фото предмета')),
                ('on_time', models.CharField(max_length=30, verbose_name='Время курса ')),
                ('price', models.CharField(max_length=30, verbose_name='Курс стоить')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=3, verbose_name='Имя учителя')),
                ('subject', models.CharField(max_length=30, verbose_name='Предмет')),
                ('image', models.ImageField(upload_to='media/photo/teachers/%d')),
                ('description', models.CharField(max_length=30, verbose_name='Краткое описание о учителя')),
            ],
        ),
    ]
